name: GitHub Actions Deploy
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Deploy to Production
        run: |
          ssh ${{ env.SSH_SERVER_IP }} "bash -s" < deploy.sh
          env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}